// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boxgeom.proto

#include "boxgeom.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_vector3d_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_vector3d_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Vector3d;
}  // namespace protobuf_vector3d_2eproto
namespace gazebo {
namespace msgs {
class BoxGeomDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BoxGeom>
      _instance;
} _BoxGeom_default_instance_;
}  // namespace msgs
}  // namespace gazebo
namespace protobuf_boxgeom_2eproto {
static void InitDefaultsBoxGeom() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gazebo::msgs::_BoxGeom_default_instance_;
    new (ptr) ::gazebo::msgs::BoxGeom();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gazebo::msgs::BoxGeom::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_BoxGeom =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsBoxGeom}, {
      &protobuf_vector3d_2eproto::scc_info_Vector3d.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_BoxGeom.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gazebo::msgs::BoxGeom, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gazebo::msgs::BoxGeom, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gazebo::msgs::BoxGeom, size_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::gazebo::msgs::BoxGeom)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::gazebo::msgs::_BoxGeom_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "boxgeom.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rboxgeom.proto\022\013gazebo.msgs\032\016vector3d.p"
      "roto\".\n\007BoxGeom\022#\n\004size\030\001 \002(\0132\025.gazebo.m"
      "sgs.Vector3d"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 92);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "boxgeom.proto", &protobuf_RegisterTypes);
  ::protobuf_vector3d_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_boxgeom_2eproto
namespace gazebo {
namespace msgs {

// ===================================================================

void BoxGeom::InitAsDefaultInstance() {
  ::gazebo::msgs::_BoxGeom_default_instance_._instance.get_mutable()->size_ = const_cast< ::gazebo::msgs::Vector3d*>(
      ::gazebo::msgs::Vector3d::internal_default_instance());
}
void BoxGeom::clear_size() {
  if (size_ != NULL) size_->Clear();
  clear_has_size();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BoxGeom::kSizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BoxGeom::BoxGeom()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_boxgeom_2eproto::scc_info_BoxGeom.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:gazebo.msgs.BoxGeom)
}
BoxGeom::BoxGeom(const BoxGeom& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_size()) {
    size_ = new ::gazebo::msgs::Vector3d(*from.size_);
  } else {
    size_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:gazebo.msgs.BoxGeom)
}

void BoxGeom::SharedCtor() {
  size_ = NULL;
}

BoxGeom::~BoxGeom() {
  // @@protoc_insertion_point(destructor:gazebo.msgs.BoxGeom)
  SharedDtor();
}

void BoxGeom::SharedDtor() {
  if (this != internal_default_instance()) delete size_;
}

void BoxGeom::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BoxGeom::descriptor() {
  ::protobuf_boxgeom_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_boxgeom_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BoxGeom& BoxGeom::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_boxgeom_2eproto::scc_info_BoxGeom.base);
  return *internal_default_instance();
}


void BoxGeom::Clear() {
// @@protoc_insertion_point(message_clear_start:gazebo.msgs.BoxGeom)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(size_ != NULL);
    size_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool BoxGeom::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gazebo.msgs.BoxGeom)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .gazebo.msgs.Vector3d size = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_size()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gazebo.msgs.BoxGeom)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gazebo.msgs.BoxGeom)
  return false;
#undef DO_
}

void BoxGeom::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gazebo.msgs.BoxGeom)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .gazebo.msgs.Vector3d size = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_size(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gazebo.msgs.BoxGeom)
}

::google::protobuf::uint8* BoxGeom::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gazebo.msgs.BoxGeom)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .gazebo.msgs.Vector3d size = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_size(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gazebo.msgs.BoxGeom)
  return target;
}

size_t BoxGeom::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gazebo.msgs.BoxGeom)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required .gazebo.msgs.Vector3d size = 1;
  if (has_size()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *size_);
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BoxGeom::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gazebo.msgs.BoxGeom)
  GOOGLE_DCHECK_NE(&from, this);
  const BoxGeom* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BoxGeom>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gazebo.msgs.BoxGeom)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gazebo.msgs.BoxGeom)
    MergeFrom(*source);
  }
}

void BoxGeom::MergeFrom(const BoxGeom& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gazebo.msgs.BoxGeom)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_size()) {
    mutable_size()->::gazebo::msgs::Vector3d::MergeFrom(from.size());
  }
}

void BoxGeom::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gazebo.msgs.BoxGeom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BoxGeom::CopyFrom(const BoxGeom& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gazebo.msgs.BoxGeom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoxGeom::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (has_size()) {
    if (!this->size_->IsInitialized()) return false;
  }
  return true;
}

void BoxGeom::Swap(BoxGeom* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BoxGeom::InternalSwap(BoxGeom* other) {
  using std::swap;
  swap(size_, other->size_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BoxGeom::GetMetadata() const {
  protobuf_boxgeom_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_boxgeom_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace msgs
}  // namespace gazebo
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::gazebo::msgs::BoxGeom* Arena::CreateMaybeMessage< ::gazebo::msgs::BoxGeom >(Arena* arena) {
  return Arena::CreateInternal< ::gazebo::msgs::BoxGeom >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
