// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MultiplevectorVisual.proto

#include "MultiplevectorVisual.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_VectorVisual_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_VectorVisual_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_VectorVisual;
}  // namespace protobuf_VectorVisual_2eproto
namespace ssm_msgs {
namespace msgs {
class MultiplevectorVisualDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MultiplevectorVisual>
      _instance;
} _MultiplevectorVisual_default_instance_;
}  // namespace msgs
}  // namespace ssm_msgs
namespace protobuf_MultiplevectorVisual_2eproto {
static void InitDefaultsMultiplevectorVisual() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ssm_msgs::msgs::_MultiplevectorVisual_default_instance_;
    new (ptr) ::ssm_msgs::msgs::MultiplevectorVisual();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ssm_msgs::msgs::MultiplevectorVisual::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_MultiplevectorVisual =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsMultiplevectorVisual}, {
      &protobuf_VectorVisual_2eproto::scc_info_VectorVisual.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_MultiplevectorVisual.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ssm_msgs::msgs::MultiplevectorVisual, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ssm_msgs::msgs::MultiplevectorVisual, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ssm_msgs::msgs::MultiplevectorVisual, vectors_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::ssm_msgs::msgs::MultiplevectorVisual)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ssm_msgs::msgs::_MultiplevectorVisual_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "MultiplevectorVisual.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032MultiplevectorVisual.proto\022\rssm_msgs.m"
      "sgs\032\022VectorVisual.proto\"D\n\024Multiplevecto"
      "rVisual\022,\n\007vectors\030\001 \003(\0132\033.ssm_msgs.msgs"
      ".VectorVisual"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 133);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MultiplevectorVisual.proto", &protobuf_RegisterTypes);
  ::protobuf_VectorVisual_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_MultiplevectorVisual_2eproto
namespace ssm_msgs {
namespace msgs {

// ===================================================================

void MultiplevectorVisual::InitAsDefaultInstance() {
}
void MultiplevectorVisual::clear_vectors() {
  vectors_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MultiplevectorVisual::kVectorsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MultiplevectorVisual::MultiplevectorVisual()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MultiplevectorVisual_2eproto::scc_info_MultiplevectorVisual.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ssm_msgs.msgs.MultiplevectorVisual)
}
MultiplevectorVisual::MultiplevectorVisual(const MultiplevectorVisual& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      vectors_(from.vectors_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ssm_msgs.msgs.MultiplevectorVisual)
}

void MultiplevectorVisual::SharedCtor() {
}

MultiplevectorVisual::~MultiplevectorVisual() {
  // @@protoc_insertion_point(destructor:ssm_msgs.msgs.MultiplevectorVisual)
  SharedDtor();
}

void MultiplevectorVisual::SharedDtor() {
}

void MultiplevectorVisual::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MultiplevectorVisual::descriptor() {
  ::protobuf_MultiplevectorVisual_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MultiplevectorVisual_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MultiplevectorVisual& MultiplevectorVisual::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MultiplevectorVisual_2eproto::scc_info_MultiplevectorVisual.base);
  return *internal_default_instance();
}


void MultiplevectorVisual::Clear() {
// @@protoc_insertion_point(message_clear_start:ssm_msgs.msgs.MultiplevectorVisual)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  vectors_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool MultiplevectorVisual::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ssm_msgs.msgs.MultiplevectorVisual)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .ssm_msgs.msgs.VectorVisual vectors = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_vectors()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ssm_msgs.msgs.MultiplevectorVisual)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ssm_msgs.msgs.MultiplevectorVisual)
  return false;
#undef DO_
}

void MultiplevectorVisual::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ssm_msgs.msgs.MultiplevectorVisual)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ssm_msgs.msgs.VectorVisual vectors = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->vectors_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->vectors(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ssm_msgs.msgs.MultiplevectorVisual)
}

::google::protobuf::uint8* MultiplevectorVisual::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ssm_msgs.msgs.MultiplevectorVisual)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ssm_msgs.msgs.VectorVisual vectors = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->vectors_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->vectors(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ssm_msgs.msgs.MultiplevectorVisual)
  return target;
}

size_t MultiplevectorVisual::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ssm_msgs.msgs.MultiplevectorVisual)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .ssm_msgs.msgs.VectorVisual vectors = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->vectors_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->vectors(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MultiplevectorVisual::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ssm_msgs.msgs.MultiplevectorVisual)
  GOOGLE_DCHECK_NE(&from, this);
  const MultiplevectorVisual* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MultiplevectorVisual>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ssm_msgs.msgs.MultiplevectorVisual)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ssm_msgs.msgs.MultiplevectorVisual)
    MergeFrom(*source);
  }
}

void MultiplevectorVisual::MergeFrom(const MultiplevectorVisual& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ssm_msgs.msgs.MultiplevectorVisual)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  vectors_.MergeFrom(from.vectors_);
}

void MultiplevectorVisual::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ssm_msgs.msgs.MultiplevectorVisual)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MultiplevectorVisual::CopyFrom(const MultiplevectorVisual& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ssm_msgs.msgs.MultiplevectorVisual)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MultiplevectorVisual::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->vectors())) return false;
  return true;
}

void MultiplevectorVisual::Swap(MultiplevectorVisual* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MultiplevectorVisual::InternalSwap(MultiplevectorVisual* other) {
  using std::swap;
  CastToBase(&vectors_)->InternalSwap(CastToBase(&other->vectors_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MultiplevectorVisual::GetMetadata() const {
  protobuf_MultiplevectorVisual_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MultiplevectorVisual_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace msgs
}  // namespace ssm_msgs
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ssm_msgs::msgs::MultiplevectorVisual* Arena::CreateMaybeMessage< ::ssm_msgs::msgs::MultiplevectorVisual >(Arena* arena) {
  return Arena::CreateInternal< ::ssm_msgs::msgs::MultiplevectorVisual >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
