// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SphericalVector.proto

#ifndef PROTOBUF_INCLUDED_SphericalVector_2eproto
#define PROTOBUF_INCLUDED_SphericalVector_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_SphericalVector_2eproto 

namespace protobuf_SphericalVector_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_SphericalVector_2eproto
namespace ssm_msgs {
namespace msgs {
class SphericalVector;
class SphericalVectorDefaultTypeInternal;
extern SphericalVectorDefaultTypeInternal _SphericalVector_default_instance_;
}  // namespace msgs
}  // namespace ssm_msgs
namespace google {
namespace protobuf {
template<> ::ssm_msgs::msgs::SphericalVector* Arena::CreateMaybeMessage<::ssm_msgs::msgs::SphericalVector>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ssm_msgs {
namespace msgs {

// ===================================================================

class SphericalVector : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ssm_msgs.msgs.SphericalVector) */ {
 public:
  SphericalVector();
  virtual ~SphericalVector();

  SphericalVector(const SphericalVector& from);

  inline SphericalVector& operator=(const SphericalVector& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SphericalVector(SphericalVector&& from) noexcept
    : SphericalVector() {
    *this = ::std::move(from);
  }

  inline SphericalVector& operator=(SphericalVector&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SphericalVector& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SphericalVector* internal_default_instance() {
    return reinterpret_cast<const SphericalVector*>(
               &_SphericalVector_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SphericalVector* other);
  friend void swap(SphericalVector& a, SphericalVector& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SphericalVector* New() const final {
    return CreateMaybeMessage<SphericalVector>(NULL);
  }

  SphericalVector* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SphericalVector>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SphericalVector& from);
  void MergeFrom(const SphericalVector& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SphericalVector* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double r = 1;
  bool has_r() const;
  void clear_r();
  static const int kRFieldNumber = 1;
  double r() const;
  void set_r(double value);

  // required double theta = 2;
  bool has_theta() const;
  void clear_theta();
  static const int kThetaFieldNumber = 2;
  double theta() const;
  void set_theta(double value);

  // required double phi = 3;
  bool has_phi() const;
  void clear_phi();
  static const int kPhiFieldNumber = 3;
  double phi() const;
  void set_phi(double value);

  // @@protoc_insertion_point(class_scope:ssm_msgs.msgs.SphericalVector)
 private:
  void set_has_r();
  void clear_has_r();
  void set_has_theta();
  void clear_has_theta();
  void set_has_phi();
  void clear_has_phi();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  double r_;
  double theta_;
  double phi_;
  friend struct ::protobuf_SphericalVector_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SphericalVector

// required double r = 1;
inline bool SphericalVector::has_r() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SphericalVector::set_has_r() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SphericalVector::clear_has_r() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SphericalVector::clear_r() {
  r_ = 0;
  clear_has_r();
}
inline double SphericalVector::r() const {
  // @@protoc_insertion_point(field_get:ssm_msgs.msgs.SphericalVector.r)
  return r_;
}
inline void SphericalVector::set_r(double value) {
  set_has_r();
  r_ = value;
  // @@protoc_insertion_point(field_set:ssm_msgs.msgs.SphericalVector.r)
}

// required double theta = 2;
inline bool SphericalVector::has_theta() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SphericalVector::set_has_theta() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SphericalVector::clear_has_theta() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SphericalVector::clear_theta() {
  theta_ = 0;
  clear_has_theta();
}
inline double SphericalVector::theta() const {
  // @@protoc_insertion_point(field_get:ssm_msgs.msgs.SphericalVector.theta)
  return theta_;
}
inline void SphericalVector::set_theta(double value) {
  set_has_theta();
  theta_ = value;
  // @@protoc_insertion_point(field_set:ssm_msgs.msgs.SphericalVector.theta)
}

// required double phi = 3;
inline bool SphericalVector::has_phi() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SphericalVector::set_has_phi() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SphericalVector::clear_has_phi() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SphericalVector::clear_phi() {
  phi_ = 0;
  clear_has_phi();
}
inline double SphericalVector::phi() const {
  // @@protoc_insertion_point(field_get:ssm_msgs.msgs.SphericalVector.phi)
  return phi_;
}
inline void SphericalVector::set_phi(double value) {
  set_has_phi();
  phi_ = value;
  // @@protoc_insertion_point(field_set:ssm_msgs.msgs.SphericalVector.phi)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ssm_msgs

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_SphericalVector_2eproto
